SET FOREIGN_KEY_CHECKS = 1;

DROP SCHEMA IF EXISTS `dbCarrito` ;
CREATE SCHEMA IF NOT EXISTS `dbCarrito`;

CREATE TABLE IF NOT EXISTS `dbCarrito`.`iArticulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreArticulo` VARCHAR(100) NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `urlImagen` VARCHAR(200) NULL DEFAULT 'producto.png',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci

CREATE TABLE IF NOT EXISTS `dbCarrito`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `permisos` VARCHAR(100) NULL DEFAULT NULL,
  `validado` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
  
SET FOREIGN_KEY_CHECKS = 1;
